services:
  - type: web
    name: lgu-ims-backend
    env: docker
    plan: starter # or free
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: APP_NAME
        value: LGU IMS
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_LEVEL
        value: error
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        value: mysql
      - key: DATABASE_URL
        fromDatabase:
          name: lgu-ims-db
          property: connectionString

databases:
  - name: lgu-ims-db
    plan: starter # or free
    databaseName: lgu_ims
    user: lgu_user